{{- define "acton_file_template" }}
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.
    actions:
    {{- range $index, $action := .Values.curator.actions }}
      {{ add $index 1 }}:
        action: {{ $action.action}}
        description: {{ $action.description }}
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        {{- if hasKey $action "filters" }}
        filters:
        {{- range .filters }}
        {{- if eq ( .type | toString ) "age" }}
        - filtertype: {{ .type }}
          source: {{ .source }}
          direction: {{ .direction }}
          timestring: {{ .timestring | toString | quote }}
          unit: {{ .unit }}
          unit_count: {{ .unit_count }}
          field:
          stats_result:
          epoch:
          exclude: {{ .exclude }}
        {{- end }}
        
        {{- /* end Filters iteration */ -}}
        {{- end }}
        
        {{- /* end Filters test */ -}}
        {{- end }}
        
        {{- /* end Actions iteration */ -}}
        {{- end }}
{{end}}

{{- if .Values.curator.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-curator-config
  labels:
    component: curator
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  action_file.yml: |-
    ---
    {{- template "acton_file_template" . }}
  
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - {{ template "fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.tls.clusterDomain }}
      port: {{ .Values.service.httpPort }}
      url_prefix:
      {{- if .Values.tls.enable }}
      use_ssl: True
      certificate: /tls/ca.crt
      client_cert: /tls/tls.crt
      client_key: /tls/tls.key
      ssl_no_validate: False
      {{- else }}
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      {{- end }}
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: DEBUG
      logfile:
      logformat: json
      blacklist: [] #['elasticsearch', 'urllib3']
{{- end }}